### PR TITLE
A pile of modernization

### PR DESCRIPTION
**Pull request by tas50**
1 change per commit. Move to custom resources, install the gem automatically, extend auth options, improve error logging, add support for debian/ubuntu.

### CODE REVIEW

**Comment by swalberg** [comment]
Thank you! Let me go over this. Appreciate the breakdown of the commits.

**Comment by tas50** [comment]
1 more incoming to add Debian/Ubuntu support

**Comment by tas50** [comment]
@swalberg any feedback on this?

**Comment by swalberg** [comment]
Hi, I got about half way though the commits before I had to move on to something else. On my list of things to finish this week. Thanks, and sorry for how long it's taking.

**Comment by tas50** [comment]
No need to apologize. Everyone gets busy

**Comment by swalberg** [comment]
Thanks for putting this together. I learned a lot about modern Chef style. The gem loading thing is clever and will save time, too. Going to merge this and cut a release.

**Pull request merged**
